menu:
  主页: /
  归档: /archives
  分类: /categories

# gitment
gitment: false
gitment_owner:
gitment_repo:
gitment_client_id:
gitment_client_secret:

# gitalk
gitalk: false
gitalk_owner:
gitalk_admin: []
gitalk_repo:
gitalk_client_id:
gitalk_client_secret:

# valine comment
valine: false
leancloud_id:
leancloud_key:

# disqus comment
disqus: false
disqus_shortname:

# utterances comment
utterances: false
utterances_repo:

# livere city comment
livere: false
livere_data_uid:

# giscus comment
giscus: false
data_repo: 
data_repo_id: 
data_category: 
data_category_id: 
data_mapping: pathname
#data_term: 
data_strict: 0
data_reactions_enabled: 0
data_emit_metadata: 0
data_input_position: top
data_loading: 
data_lang: en

# google analytics
googleTrackId:

# baidu analytics
baiduTrackId:

# whether to show read more button when showing article in excerpt in main page
read_more_btn: true

lightgallery:
    # if you don't specify the css or js source, the default cdn will be used.
    # css: # css source url
    # js: #js source url
    # sorry that I can not find any cdn hosting following plugins,
    # please self-host the plugin js and add url here
    # plugins:
        # lg-thumbnail:
        # lg-zoom:
        # lg-autoplay:
        # lg-fullscreen:
        # lg-pager:
